import { getServerSession } from "next-auth";
import { SessionProvider } from "../components/SessionProvider";
import "./globals.css";
import { authOptions } from "../pages/api/auth/[...nextauth]";
import UserLogin from "../components/UserLogin";
import Header from "../components/Header";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  session: false;
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {!session ? (
            <div>
              <UserLogin />
            </div>
          ) : (
            <div>
              <div className="sticky top-0 bg-white">
                <Header />
              </div>
              <div>{children}</div>
            </div>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}
